### ISSUE TITLE
Property `placeholder` is not localized in Bootstrap4 version

### ISSUE THREAD

**Issue by sisidra** [adrianhurt/play-bootstrap#100]
`B4FieldInfo` overrides `innerArgsMap` without calling or fully reimplementing `BSFieldInfo.innerArgsMap` behaviour, like `placeholder` property i18n.

**Comment by sisidra** [comment]
Here is a corresponding PR: https://github.com/adrianhurt/play-bootstrap/pull/101

**Comment by adrianhurt** [comment]
Thanks @sisidra !

Sorry for answering you so late. These days are totally imposible for me to check it and test it. So, please, you will to wait a bit more (maybe a week). 

Thanks again!

**Comment by mkurz** [comment]
@adrianhurt Are you still working on this libary?

**Comment by adrianhurt** [comment]
Sorry for answering so late. I'm now releasing the version 1.2.1-P2X-BX-SNAPSHOT with the PR merged. I'll hope to be able to update the documentation page during the next week.
