### ISSUE TITLE
Wrong reference

### ISSUE THREAD

**Issue by nandotorterolo** [adrianhurt/play-bootstrap#102]
https://adrianhurt.github.io/play-bootstrap/

Every helper you need
Inputs, checkboxes, radio buttons, selects, input-groups, custom inputs, ... You have the essential input helpers you could need. But this library is for the community, so you can collaborate or ask for others.
See the list of available helpers `_here_`.

https://adrianhurt.github.io/play-bootstrap/docs#helpers

**Comment by adrianhurt** [comment]
Finally I fixed the redirections issues (I hope so). Thanks and sorry for fixing it so late. Sorry!
