### ISSUE TITLE
Make my own radio button?

### ISSUE THREAD

**Issue by bharal** [adrianhurt/play-bootstrap#108]
Been banging my head on this one - i want the radio button to render like this:

```
<div class="btn-group" data-toggle="buttons">
      <label class="btn btn-primary">
        <input type="radio" name="options" id="option1"> Option 1
      </label>
      <label class="btn btn-primary">
        <input type="radio" name="options" id="option2"> Option 2
      </label>
      <label class="btn btn-primary">
        <input type="radio" name="options" id="option3"> Option 3
      </label>
</div>

```
Sadly, I have no idea how to reach this nirvana. I've tried making my own constructor, but nothing ever compiles - is there a github example of just a custom field constructor that works that i can use>?

**Comment by adrianhurt** [comment]
Sorry @bharal, I know it's too late. Did you solved the problem?
