### ISSUE TITLE
Install / Usage instructions

### ISSUE THREAD

**Issue by cybex-dev** [adrianhurt/play-bootstrap#109]
Hi

Thanks for the work you have done!

Could you provide installation instructions in the `ReadMe.md`. 

**Reason**: I am unsure of how to incorporate `play-bootstrap` correctly into my own project, and I can imagine not being the only one..

Thanks in advance

**Comment by adrianhurt** [comment]
Hi, there is a link to the documentation page in the readme. There, you can see a section with the installation instructions.

https://adrianhurt.github.io/play-bootstrap/#installation

I hope it helps you
