### ISSUE TITLE
Checkbox label in horizontal form not vertically aligned

### ISSUE THREAD

**Issue by NTPape** [adrianhurt/play-bootstrap#113]
Hi,

I'm using the version 1.4-P26-B4-SNAPSHOT and noticed the following minor issue:

When using a checkbox in a horizontal form with a label they will not be vertically aligned because the label has the `col-form-label` class giving it a positive `padding-top` while the checkbox has none. According to the [Bootstrap docs](https://getbootstrap.com/docs/4.1/components/forms/#horizontal-form) that class should not be used for labels of checkboxes, or could be solved similar to how it's done with radios in the linked example where they add a `pt-0` in addition to the `col-form-label` to force `padding-top: 0`.

I haven't tested it, but this should be no problem in Bootstrap 3 because the `checkbox` has the same `padding-top: 7px;` as the `control-label` there, see [here](https://getbootstrap.com/docs/3.3/css/#forms-horizontal).

Thanks for all the work you've been putting into this! :)

**Comment by adrianhurt** [comment]
Sorry @NTPape, I know it's too late... You were right, however, that's an "issue" of Bootstrap, not this plugin. You can solve it easily with a bit of your own CSS, but I suppose you solved this problem a long time ago... 😄
