### ISSUE TITLE
documentation misses class "position-relative" for feedback tooltip

### ISSUE THREAD

**Issue by jenshuehn** [adrianhurt/play-bootstrap#114]
Dear Adrian. 

There is a minor observation which I would like to report as this is an unnecessary hurdle:

Bootstrap 4.1 requires (https://getbootstrap.com/docs/4.1/components/forms/#tooltips):
_If your form layout allows it, you can swap the .{valid|invalid}-feedback classes for .{valid|invalid}-tooltip classes to display validation feedback in a styled tooltip. Be sure to have a parent with position: relative on it for tooltip positioning. _

Unfortunately, in the documentation ( http://adrianhurt.github.io/play-bootstrap/1.4-P26-B4/docs/#helpers-validation-states ) this is missing ('_class -> "position-relative") which leads to an off positioning of the tooltip. However, in the sample code provided on Github it is there.

All the best.
Jens

**Comment by adrianhurt** [comment]
Sorry to fix it so late.
