### ISSUE TITLE
Play 2.7 support (and cross build for Scala 2.13.0-M5)

### ISSUE THREAD

**Issue by mkurz** [adrianhurt/play-bootstrap#115]
Please add support for Play 2.7.
https://blog.playframework.com/play-2-7-0-is-here/
https://www.playframework.com/documentation/2.7.x/Highlights27
https://www.playframework.com/documentation/2.7.x/Migration27

Please also publish builds for Scala `2.13.0-M5`. ([Add it to `crossScalaVersions`](https://github.com/adrianhurt/play-bootstrap/blob/48c02e367eb89b952904e9e514e12bfac6b68e08/play26-bootstrap4/module/build.sbt#L7), also please update to latest 2.12 and latest 2.11)
Your probably have to set `PlayKeys.playOmnidoc := false` in `build.sbt` to make it work.

Also it _could_ be that you have to adjust some twirl templates because now curly brackets are needed in some cases.
E.g. twirl code like
```html
@something.map { case SomeThing(foo) =>
	some html
}
```
becomes this:
```
@something.map { case SomeThing(foo) => {
	some html
}}
```

**Comment by adrianhurt** [comment]
Hi @mkurz! I've just finally released the snapshots for 1.5 versions with Play 2.7 (the code is on branch develop). Please, try to test it. I've just found a lot of warnings like this one:

```
[warn] /path/to/play-bootstrap/play27-bootstrap4/module/app/views/b4/buttonType.scala.html:4:16:
Passing an explicit array value to a Scala varargs method is deprecated (since 2.13.0) and will result in a defensive copy;
Use the more efficient non-copying ArraySeq.unsafeWrapArray or an explicit toIndexedSeq call
[warn] }(fc, msgsProv)
```

I'll try to check them as soon as possible and to update the docs as well.

The snapshots versions are:
* 1.5-P27-B4-SNAPSHOT
* 1.5-P26-B4-SNAPSHOT

**Comment by mkurz** [comment]
@adrianhurt Thanks! I will check it out as soon as possible! Again thank you very much for your efforts!

**Comment by bjoernhaeuser** [comment]
I tested the 2.7 snapshot and it looks very good to me, though I only have a minor use case - two simple forms.

**Comment by mkurz** [comment]
I think we should wait with the next release until next week because then Scala 2.13 will be released and also Play will be published for Scala 2.13 - meaning also play-bootstrap can then also published for Scala 2.13 as well.

**Comment by adrianhurt** [comment]
Yes, I think it’s better to wait as well. I’d only update something to fix bugs if needed, but please, test it if you all have time.

**Comment by bjoernhaeuser** [comment]
Scala 2.13 is now released, looking forward to the release of `play-boostrap`. Thank you!

**Comment by mkurz** [comment]
@bjoernhaeuser yes but we need Play to support Scala 2.13 first

**Comment by ahjohannessen** [comment]
https://github.com/playframework/playframework/releases/tag/2.7.3

**Comment by adrianhurt** [comment]
Great! I’ll try to update it this weekend!

**Comment by mkurz** [comment]
@adrianhurt I will submit a pull request later today with an important fix. Please wait for it, thanks!

**Comment by mkurz** [comment]
Please don't release yet, as I said will provide a pull request with a bugfix very soon!

**Comment by adrianhurt** [comment]
Don't worry, I'll wait for it.

**Comment by mkurz** [comment]
@adrianhurt Done, see #121 (also maybe merge #120 before).
Let me know if you need help. Thanks!

**Comment by adrianhurt** [comment]
Hi! I've just released versions 1.5-P2X-BX-RC-SNAPSHOT with Play 2.7.3 (note the **-RC**). If you don't see any problem I'll release the final one during the next week.

I've noted the syntax `'foo` for a symbol has been deprecated, so I suppose in the version 1.6 I'll substitute (maybe) every symbol by a simple string.

**Comment by mkurz** [comment]
@adrianhurt Just did a small test, for me it looks good, thanks!

**Comment by bjoernhaeuser** [comment]
Same here :) small test was successful! Thanks!

**Comment by adrianhurt** [comment]
Hey guys! It's finally released

**Comment by mkurz** [comment]
Thanks!

**Comment by mkurz** [comment]
> I've noted the syntax 'foo for a symbol has been deprecated, so I suppose in the version 1.6 I'll substitute (maybe) every symbol by a simple string.

That is what Play itself will do as well: See https://github.com/playframework/playframework/issues/9447 and https://github.com/playframework/playframework/pull/9488. Therefore `'key -> "value"` will become `"key" -> "value"`...

**Comment by fooblahblah** [comment]
Any updates on the Symbol deprecation thing? I'm trying to get our app compiling under 2.13.1 and the last issue is the Play template using literal Symbols. I migrated to the `Symbol("foo")` syntax, but get some implicit errors, but maybe it's unrelated?

```
could not find implicit value for parameter fc: views.html.b3.package.B3FieldConstructor
[error]               @b3.select(catForm("categoryType"), categoryTypeSelectOptions, Symbol("_label") -> "Category Type")
```

**Comment by mkurz** [comment]
@fooblahblah No updates yet. I think the implicit error you face is not related to symbols.

**Comment by fooblahblah** [comment]
Thanks @adrianhurt. I'm starting to think the same. I need to figure out why these usages started breaking when I changed versions of the library.

**Comment by mkurz** [comment]
See #124 for the symbol issue.
