### ISSUE TITLE
Combining @multifield and @repeat

### ISSUE THREAD

**Issue by woyzeck** [adrianhurt/play-bootstrap#116]
Hi, I've tried to render multiple `@b4.checkboxes` in a single row using `@multifield` (based on the example in your docs). However, my list of checkboxes isn't static. Instead of that it will be backed by a Seq of entries that are read from a database - every db record will be shown as a checkbox.
Play suggests using `repeat` or `repeatWithIndex` to iterate over the Seq, which works like a charm, but this approach seems to be incompatible with the approach `multifield` takes.

Do you have any ideas of how this could be achieved with @b4 ?

**Comment by adrianhurt** [comment]
Hi @woyzeck, you should be able to use both options.

`repeat` helper lets you render a list of "form-groups".
```
@helper.repeat(myForm("foo"), min = 1) { fooField =>
    @b4.checkbox(field, fieldArgs:_*)
}
```

And the multifield feature of this library is intended to render a list of fields within the same "form-group".
```
val seqOfFieldAndArgs: Seq[(Field, Seq[(Symbol,Any)])] = ...

@b4.multiCheckbox(seqOfFieldAndArgs:_*)(...)
```

**Comment by woyzeck** [comment]
Thank you, @adrianhurt. I'll give that a try.

This would require to accumulate the calls inside repeat while at the same time returning an empty html snippet and using `multifield` later to generate the real html snippet.

**Comment by adrianhurt** [comment]
Hi @woyzeck, did you solved the problem?

**Comment by woyzeck** [comment]
Hi @adrianhurt , yes, thx to your hints I was able to solve this issue.
