### ISSUE TITLE
Play 2.8

### ISSUE THREAD

**Issue by mkurz** [adrianhurt/play-bootstrap#125]
Play 2.8 released:
https://blog.playframework.com/play-2-8-0-released/

@adrianhurt Please merge #124 before working on 2.8 support (so when copying the directories the fix is included already in the new folder structure)

**Comment by mkurz** [comment]
Ping @adrianhurt

**Comment by mkurz** [comment]
Hey @adrianhurt, can you cut the release?

**Comment by ahjohannessen** [comment]
@adrianhurt It would be nice to get a new release that supports play 2.8 :)

**Comment by slugmandrew** [comment]
@adrianhurt Let us know if there is anything you need help with!

**Comment by mkurz** [comment]
Ping @adrianhurt, I hope you are ok!

**Comment by adrianhurt** [comment]
Sorry for my unjustifiable delay! I've just merged it. I will also merge #126 and publish a snapshot

**Comment by adrianhurt** [comment]
Hi again! I've just published the versions:
- 1.6-P28-B4-SNAPSHOT
- 1.6-P28-B3-SNAPSHOT
- 1.6-P27-B4-SNAPSHOT
- 1.6-P27-B3-SNAPSHOT
- 1.6-P26-B4-SNAPSHOT
- 1.6-P26-B3-SNAPSHOT

And sorry again for the delay!! I'll try to update the docs as soon as possible

**Comment by mkurz** [comment]
Thanks you very much @adrianhurt! Great work! I will use try the snapshots asap. Have a nice weekend!

**Comment by mkurz** [comment]
@adrianhurt Can you release the final version? I tested the snapshot in our projects, everything looks perfect. Actually there are no changes, besides #124.
Can you also merg #128 before cutting the release? Thanks!

**Comment by adrianhurt** [comment]
Here you have! I forgot to merge it before, so I've just release not only version 1.6 but also 1.6.1 😅 
- 1.6.1-P28-B4
- 1.6.1-P28-B3
- 1.6.1-P27-B4
- 1.6.1-P27-B3
- 1.6.1-P26-B4
- 1.6.1-P26-B3

**Comment by adrianhurt** [comment]
And now the docs are updated as well

**Comment by mkurz** [comment]
Thanks a lot for you time @adrianhurt!
You just made a small mistake, see #129
