### ISSUE TITLE
How to set data-browse attribute at custom-file input

### ISSUE THREAD

**Issue by cyrus07424** [adrianhurt/play-bootstrap#131]
I wanna change "Browse" text at custom-file input's label.

how to set "data-browse" attribute?

https://getbootstrap.com/docs/4.5/components/forms/#translating-or-customizing-the-strings-with-html

**Comment by adrianhurt** [comment]
Sorry @cyrus07424 , but the file helper does not allow add custom attributes to the label tag. You can try using SCSS (https://getbootstrap.com/docs/4.5/components/forms/#translating-or-customizing-the-strings-with-scss) or creating your own helper (https://adrianhurt.github.io/play-bootstrap/1.6-P28-B4/extend-it/)

**Comment by cyrus07424** [comment]
I see. Thank you.
