### ISSUE TITLE
HTML5 data form validation - Password max length

### ISSUE THREAD

**Issue by thomaslhostis** [adrianhurt/play-bootstrap#45]
Your HTML5 data form validation is a great feature. There is only one case where, in my experience, it shouldn't apply. When a user defines a password, if the password is longer than the input field can contain, the user won't be able to see that his input is being truncated, *if you set a max length*.

![screen shot 2016-01-16 at 23 19 55](https://cloud.githubusercontent.com/assets/4296630/12374797/b97e1350-bca7-11e5-9d80-bf7a29d58481.png)

Of course, this can be avoided by simply **not setting a max length** on this particular form field. But, if it is considered bad practice, shouldn't we just not permit it? It might spare some fellows an unpleasant situation? What do you think?

**Comment by adrianhurt** [comment]
Hi @thomaslhostis. I'm not really sure…

Thinking about this, anyway, I've just released a simple fix to be able to get rid of any constraint value in templates if you need it. You can now set `'maxlength -> false` and it will not render it (but the controller will complaint while handling the form). With that, it's very easy to add this default argument only for the `password` helper. But I'm not sure if it could be confusing the fact of using different behavior only for the `password` helper. And what about a possible pattern matching? Should we do the same? I think it could be better to give this option to disable this constraint only for templates and then anyone could choice.

**Comment by thomaslhostis** [comment]
I agree. To answer your question: it wouldn't be the same with pattern matching because it wouldn't prevent the user from typing anything.

Thank you

**Comment by mkurz** [comment]
So for password fields the max length constraint is still set?
Do I have to disable it by hand?

**Comment by adrianhurt** [comment]
I'm not sure what you mean. For a password field, you can choose to add a max length constraint within your controller, and it will be rendered automatically in your view by `@b3.password` as normal. But if you want to have a max length constraint in your controller but not in your view, you could do it adding `'maxlength -> false` to your `@b3.password` (it works for any constraint and helper).

In my opinion, I would recommend adding a max length constraint (in controller and view) when you are setting a new password, and not using it when you are putting your password to log in. But if anyone wants to add a constraint only in controller, this is the solution.

**Comment by mkurz** [comment]
Thanks, I will use `'maxlength -> false`.
