### ISSUE TITLE
Play's own select tag changed

### ISSUE THREAD

**Issue by mkurz** [adrianhurt/play-bootstrap#46]
Hi @adrianhurt 

Please have a look at:
https://github.com/playframework/playframework/pull/5399
It changes Play's own `@helper.select(...)` tag

Does this change somehow influence play-bootstrap? Do you use the Play helper tags?
If not, just close this issue.

**Comment by adrianhurt** [comment]
Thanks to notify me! But don't worry. I used the Play helper tags as a reference, but I don't use their codes.
