### ISSUE TITLE
Issue with file uploads and CSRF

### ISSUE THREAD

**Issue by Langstra** [adrianhurt/play-bootstrap#48]
`@b3.formCSRF(action = routes.Employees.save_import(), 'enctype -> "multipart/form-data") {

                <div class="form-group" id="picture_field">
                    <label for="picture">picture</label>
                    <input type="file" name="picture" id="picture" value="">
                    <p class="help-block">Upload picture.</p>
                </div>

                <input type="submit" class="btn btn-primary" value="Import">

                }`

I get the error "Invalid CSRF token found in form body" when submitting.

This is due to the fact that play2 checks the multipartform per 100kb. If the file is larger than 100kb the CSRF-token is not in the first part and play2 gives the error. I think this can be solved by adding the hidden CSRF-field at first.

**Comment by adrianhurt** [comment]
Hi @Langstra, could you try this?
```
@b3.form(... your code ...) {
  @helper.CSRF.formField(token)
  ... your code ...
}
```
Thanks!

**Comment by adrianhurt** [comment]
Sorry, this
```
@b3.form(... your code ...) {
  @CSRF.formField
  ... your code ...
}
```

**Comment by Langstra** [comment]
Thanks for your response. Your solution worked, however, the formCSRF is designed for this I think. Are there good reasons not to do this in the formCSRF tag?

**Comment by adrianhurt** [comment]
Thanks for find the bug and solve it :stuck_out_tongue_winking_eye: . No, there is no reason, I just wanted to check your proposed solution. I'll fix it quickly

Thanks!

**Comment by Langstra** [comment]
Cool, great to see that this plugin is supported so well. Great job!

**Comment by adrianhurt** [comment]
Thanks! It's fixed now, but maybe it could take a while to be updated at the snapshot's repository. Try in a while and don't forget to clean your project to be sure the library is refreshed.
