### ISSUE TITLE
Play 2.5 support

### ISSUE THREAD

**Issue by mkurz** [adrianhurt/play-bootstrap#53]
Hi! Play 2.5 was released yesterday.

**Comment by mkurz** [comment]
Notes for 2.5:
sbt version is now 0.13.11
Scala 2.10 was dropped, Scala version should be 2.11.7 only.

**Comment by adrianhurt** [comment]
Thanks. I'll check it as soon as possible.

**Comment by daddykotex** [comment]
Thanks for the library, if you need any help, I'd be glad to help.

**Comment by adrianhurt** [comment]
Thanks for your proposition, @daddykotex. I appreciate that. For the moment, my intention is to simply maintain the library, so I hope to have enough time to do it. But I'm open to receive any PR for new features if they are interesting.

I've just uploaded the new versions __1.0-P5-B3-SNAPSHOT__ and __1.0-P5-B4-SNAPSHOT__. I'll update the docs as soon as possible.
