### ISSUE TITLE
How can i load values dynamically to a b3.select?

### ISSUE THREAD

**Issue by andrefbmaximino** [adrianhurt/play-bootstrap#55]
How can i add values to a select dynamically? I need to load the values to a select based on the values of another select box. How can i load values to the select, with the JSON that i receive in the AJAX call?

**Comment by adrianhurt** [comment]
Hi, this is not a question for this library. You can do this using AJAX as usual. For example, if you are using jQuery, you can see information here:
https://www.google.es/search?q=jquery+populate+select+list+from+json
