### ISSUE TITLE
checkbox value is always true

### ISSUE THREAD

**Issue by daddykotex** [adrianhurt/play-bootstrap#56]
Maybe I'm doing something wrong but I can't figure out what:

```
@b3.checkbox( fooForm("myCheckbox"), 'value -> "test")
```
Translates to:
```
<div class="form-group  " id="myCheckbox_field">
    <div class="checkbox">
        <label for="myCheckbox">
            <input id="myCheckbox" name="myCheckbox" value="true" type="checkbox">
        </label>
    </div>
</div>
```

If I add the readonly option, the hidden field will have the correct value:
```
<div class="form-group  " id="myCheckbox_field">
    <div class="checkbox checkbox-group disabled">
        <label for="myCheckbox">
            <input id="myCheckbox" name="myCheckbox" value="true" disabled="true" readonly="true" type="checkbox">
        </label>
        <input name="myCheckbox" value="test" type="hidden">
    </div>
</div>
```

If you can confirm this is a bug, I'd be glad to fix it and submit a PR.

Thanks for your work by the way.

**Comment by adrianhurt** [comment]
Hi @daddykotex. Which version are you using? In my case, I get the following for the first case:

```
<div class="form-group  " id="myCheckbox_field">
  <div class="checkbox">
    <label for="myCheckbox">
      <input type="checkbox" id="myCheckbox" name="myCheckbox" value="test" checked="">
    </label>
  </div>
</div>
```

**Comment by daddykotex** [comment]
Thanks for the quick reply:
```
"com.adrianhurt"    %%  "play-bootstrap3"           % "0.4.5-P24"
```
along with play 2.4.6: `addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.4.6")`

**Comment by adrianhurt** [comment]
Then, this is not a bug. You can see the documents of that version (here)[http://adrianhurt.github.io/play-bootstrap/0.4.5-P24/docs/#helper-checkbox]. The custom value for checkboxes is a feature for version 1.0. For earlier versions the value can be "true" or "false".

You can try with version 1.0-P24-B3-SNAPSHOT

**Comment by daddykotex** [comment]
Oh my bad, I was looking at the wrong doc page... It's my bad, thank you very much

**Comment by daddykotex** [comment]
Another question while I'm at it, I've updated to 1.0 and now I can see the correct value being assigned but the form is always filled. I am probably missing something but why is it like that? 

I would like to build a a table and put a checkbox in each row to allow an action to be performed on the selected rows, I thought about the checkbox with a value equals to the id of the entity show in the row. But if I specify the value, then the checkbox is checked. the test clearly show that this is expected behavior, but I'm wondering why?

**Comment by adrianhurt** [comment]
You're right, I think the behavior is not the more logic one. The problem here is that we have to decide the correct value of `checked` depending on:
* a default value
* the filled value
* a possible forced value (not default)

I think I will release this version as it is, and then resolve this issue in a next version 1.1 or 1.0.1.

One possibility is:
* `'value` only sets the value, not checked attribute.
* `'_default` lets set a default
* `'checked ` forces the checked attribute.
Everyone as String values, so:
```
@b3.checkbox( fooForm("foo"), 'value -> "test")  // checked only if the field is filled to "test"
@b3.checkbox( fooForm("foo"), 'value -> "test", '_default -> "true")  // -> the same but checked if the field is unfilled
@b3.checkbox( fooForm("foo"), 'value -> "test", 'checked -> "true")  // -> always checked
```

**Comment by daddykotex** [comment]
Ok, I like the idea.

Maybe I just don't understand how I should implement my use case. The checkbox is definitely the input type I'm looking for, but maybe my form field is incorrect. I currently use:
```
val prepareUploadForm = Form(
    "selectedItems" -> seq(longNumber)
  )
```
and I build my form like that:
```
@items.map{ item =>
                <tr>
                    <td>@b3.checkbox(uploadForm(s"selectedItems[]"), 'value -> item.id)</td>
                </tr>
                }
```

In my controller I received the list of selected ids. Can you think of a way I could you your helper to avoid having all of my fields checked by default?

**Comment by adrianhurt** [comment]
Yes, you're right. It's an error of the library. I thought, you could write:
```
@b3.checkbox(uploadForm(s"selectedItems[]"), 'value -> item.id, 'checked -> "false")
```
But it doesn't works.

It's not still documented but you can now try with new version 1.1-P24-B3-SNAPSHOT. For now it's exactly the same but now you can:
* Set a default checked with `'_default`.
* Force the checked value directly with `'checked`.
* Now `'value` argument is totally independent from `checked` attribute.

So now, if you want to have the filled value (but unchecked by default), you can write:
```
@b3.checkbox(uploadForm("selectedItems[]"), 'value -> item.id)
```
And if you want to force it to always false (unchecked), try with:
```
@b3.checkbox(uploadForm("selectedItems[]"), 'value -> item.id, 'checked -> false)
```

I will add this version to the documentation as soon as possible

**Comment by adrianhurt** [comment]
I've just added version 1.1 to the docs. You can see these changes [here](http://adrianhurt.github.io/play-bootstrap/1.1-P24-B3/docs/#helper-checkbox).

**Comment by daddykotex** [comment]
Thank you so much again! :+1:
