### ISSUE TITLE
B3.email - error message wrong css?

### ISSUE THREAD

**Issue by LubomirKovalcik** [adrianhurt/play-bootstrap#57]
Hello,

if email input has some error message to display ,it resize email icon.
Example:

![errorbootstrap](https://cloud.githubusercontent.com/assets/15881431/14549831/c89b163c-02c3-11e6-9bda-e8611ddd7ee4.png)

**Comment by adrianhurt** [comment]
Hi @LubomirKovalcik.

I can't help you without the code you are using, but it should work with this:

```
@b3.inputWrapped( "email", fooForm("email"), '_label -> "Email", 'placeholder -> "example@mail.com" ) { input =>
  <div class="input-group">
    <span class="input-group-addon">@@</span>
    @input
  </div>
}
```

You can see more information [here](http://adrianhurt.github.io/play-bootstrap/1.1-P25-B3/docs/#your-inputwrapped) and [here](http://adrianhurt.github.io/play-bootstrap/1.1-P25-B3/extend-it/).

You have a problem with your HTML structure. Maybe are you using `@b3.email` helper inside the `input-group`?
