### ISSUE TITLE
Multi checkbox with value from Form

### ISSUE THREAD

**Issue by Selsynn** [adrianhurt/play-bootstrap#58]
I use v1.0 for play 2.4 and Bootstrap 3.

I have an array of checkbox of name transports[id] and value id, but I can't find how to check or not check the value from the form value.
The choices displayed by the checkbox is from a model transports where there is an id and a name (text value).

I tested 
views : 
`@b3.checkboxgroup(
  transports.map {
    case ((id, name)) =>  (searchForm(s"transports[$id]"), Seq(('_text -> name),('value -> id)))
   }.toSeq: _*)('_label -> Messages("form.filter.transport.type"), 'class -> "multi-checkbox-list")(b3.inline.fieldConstructor, implicitly[Messages])`

and 
B3/checkboxgroup.scala.html
`@(fieldsWithArgs: (Field, Seq[(Symbol,Any)])*)(globalArgs: (Symbol,Any)*)(implicit fc: b3.B3FieldConstructor, messages: Messages)
@b3.multifield(fieldsWithArgs.map(_._1):_*)(globalArgs, fieldsWithArgs.map(_._2).flatten) { implicit cfc =>
    <div @toHtmlArgs(bs.Args.inner(globalArgs).toMap)>
        @fieldsWithArgs.map { case (field, fieldArgs) =>
            @b3.checkbox(field, fieldArgs:_*)
        }
    </div>
}`

and in the views, all my checkbox are always checked. Even if I write ('checked -> "false") on the arguments, the result is always the same.
Is it normal because I don't use correctly the library or is it a bug ?

(I'm not very fluent in writing english, i'm sorry)

**Comment by adrianhurt** [comment]
Hi @Selsynn. Try using a boolean value for `'value` (i.e. the default behavior). This is a simple example, but it works for me:

```
val transports = Seq(
  "a" -> "Transport A",
  "b" -> "Transport B",
  "c" -> "Transport C"
)
val testForm = Form(tuple(
  "transports[a]" -> boolean,
  "transports[b]" -> boolean,
  "transports[c]" -> boolean
)).fill((true, false, true))
```

```
@b3.multiCheckbox(
  transports.map { case (id, name) =>
    (testForm(s"transports[$id]"), Seq('_text -> name))
  } :_*
)( '_label -> "Transports", 'class -> "multi-checkbox-list" )
```

(And don't worry for your English at all, it's perfectly understandable. At least for another non-English speaker)

**Comment by adrianhurt** [comment]
By the way, this also works:

```
val testForm = Form(tuple(
  "transports[a]" -> text,
  "transports[b]" -> text,
  "transports[c]" -> text
)).fill(("a", "", "c"))
```

```
@b3.multiCheckbox(
  transports.map { case (id, name) =>
    (testForm(s"transports[$id]"), Seq('_text -> name, 'value -> id))
  } :_*
)( '_label -> "Transports", 'class -> "multi-checkbox-list" )
```

**Comment by Selsynn** [comment]
Thanks for your prompt answer. I think I understand what I didn't understand correctly the first time around.

**Comment by adrianhurt** [comment]
Then is it solved?
