### ISSUE TITLE
Using form validation from server and has-success

### ISSUE THREAD

**Issue by Selsynn** [adrianhurt/play-bootstrap#63]
Hello,
I'm stuck with my forms and validation error / success.

1) is it normal that "has-success" is mount on the reply from server only when "showIconValid" is set at true ?
I don't want this icon, so my css prevent it from being displayed but it seems a little overkill.

2) When I displayed the form for the first time, I want the field to be black, not having "has-success" (technically, I understand there is no error, but there is no result also). Is it possible to display has-success when the form is re-submitting and nothing when it is the first time ?

Thanks

PS : I use (but I'm not sure it is very relevant)
@b3.text( form("user.lastName"), '_label -> Messages("form.last.name"), 'placeholder -> Messages("form.last.name"),'_showIconValid -> true)

**Comment by adrianhurt** [comment]
Hi @Selsynn,

[Here in the docs](http://adrianhurt.github.io/play-bootstrap/1.1-P24-B3/docs/#helpers-validation-states) you can see an example of a field with `has-success` but no icon. Your code would be like this:
```
@b3.text( form("user.lastName"), '_label -> Messages("form.last.name"), 'placeholder -> Messages("form.last.name"),'_success -> true)
```

So you must remove `'_showIconValid` and use `'_success` instead.

To get what you need in the second point, you need to use the value of `'_success`. For example, you can set it to __true__ if the request's method is __POST__.

```
@b3.text( … , '_success -> (request.method == 'POST'))
```

**Comment by Selsynn** [comment]
Thanks, I didn't try with a boolean expression, only with true and it was not what I thought.
