### ISSUE TITLE
1.1-P24-B3 for Java - could you update the example datepicker, multicheckbox, and textwithcheckbox code?

### ISSUE THREAD

**Issue by sdk451** [adrianhurt/play-bootstrap#67]
Hi - really appreciate all your work on play-bootstrap!

Is it possible to post working code examples for the multicheckbox helper for play 2.4.x and Java? Your advice to remove the implicit Messages var (to avoid conflict with PlayMagicForJava) is helpful but incomplete and I don't have the scala skills to figure out the solution. (Does seem to complile for the textwithCheckbox and datepicker helpers though!)

For example - with this version of multicheckbox.scala.html, where I have removed the implicit messages var

@(fieldsWithArgs: (Field, Seq[Symbol,Any])*)(globalArgs: (Symbol,Any)*)(implicit fc: b3.B3FieldConstructor)
@b3.multifield(fieldsWithArgs.map(_._1):_*)(globalArgs, fieldsWithArgs.map(_._2).flatten) { implicit cfc =>
  <div @toHtmlArgs(bs.Args.inner(globalArgs).toMap)>
    @fieldsWithArgs.map { case (field, fieldArgs) =>
      @b3.checkbox(field, fieldArgs:_*)
    }
  </div>
}

play gives a "wrong number of type arguments for Seq, should be 1": for lines 1, 5 and 8.

**Comment by adrianhurt** [comment]
Hi @sdk451, I think it's due to a typo error. Try with `Seq[(Symbol, Any)]` instead of `Seq[Symbol, Any]`.

**Comment by sdk451** [comment]
Sadly I had try at fixing the scala parameters following your suggestion,
still can't get it to compile. I am total novice with scala though, so it's
unsurprising.

**Comment by sdk451** [comment]
I also tried using the updated code you have for the P2.5-B3
multicheckbox.scala.html in the documentation and simply removed the
messages var - are your sure it compiles?

**Comment by adrianhurt** [comment]
No, as I told you, there is a typo in the documentation. Use `Seq[(Symbol, Any)]` instead of `Seq[Symbol, Any]`. You can see the real code [here](https://github.com/adrianhurt/play-bootstrap/blob/master/play25-bootstrap3/sample/app/views/b3/multiCheckbox.scala.html).

**Comment by adrianhurt** [comment]
What error do you have using this code (removing the messages argument)?

**Comment by adrianhurt** [comment]
Anyway, I've just fixed the typo in the docs

**Comment by sdk451** [comment]
Thanks! Got it compiling using the P25 version you directed me to and
removing the implicit messages var.
