### ISSUE TITLE
Glyphicons and @import

### ISSUE THREAD

**Issue by djahnsag** [adrianhurt/play-bootstrap#71]
We are having a problem with glyphicons in 1.0-P25-B3. It's not big (you can work around it), but we'd like to have only ONE CSS file, so it's an issue for us:

I have two projects. In one, I include Bootstrap from my HTML code and all Glyphicons work. In another, we @include the *.less files from our backend.less file. Now the path to the font files is invalid and the glyphicons aren't working anymore.

The workaround would be to include Bootstrap CSS-files from HTML, but we'd like to only have one request to a CSS-file.

I'm afraid this might also be a problem with Webjars bootstrap.

**Comment by adrianhurt** [comment]
Hi @djahnsag. Sorry, but this is actually an issue for Webjars Bootstrap or Bootstrap itself (I don't know). This library simply imports and use it. Please, try first with a simple project without this library using directly the webjar. Remember that you can exclude the default version of Bootstrap used by this library and import a specific one (check the "installation" section from the docs), so you can try with the new 3.3.7-1 version of Webjars Bootstrap ([here](https://github.com/webjars/bootstrap/issues/47) they say something about less files…)
