### ISSUE TITLE
1.1-P25-B3 with Java: "could not find implicit value for parameter messages: play.api.i18n.Messages"

### ISSUE THREAD

**Issue by Batusay2kX** [adrianhurt/play-bootstrap#73]
Hi. When trying to use play-bootstrap 1.1-P25-B3 with Play 2.5.6 in Java to create a form, I get this two compilation errors in Eclipse:

`could not find implicit value for parameter messages: play.api.i18n.Messages`

and

`not enough arguments for method apply: (implicit fc: views.html.b3.B3FieldConstructor, implicit messages: play.api.i18n.Messages)play.twirl.api.HtmlFormat.Appendable in class textarea.  Unspecified value parameter messages.`

Odd enough, even with this errors the form work without problem and as intended. The thing is that if I try to pass an `(implicit messages : Messages)` in a try to solve the first errors, I get this compilation error ALONG with the other 2 and nothing works anymore: 

```
ambiguous implicit values:
both method implicitJavaMessages in object PlayMagicForJava of type => play.api.i18n.Messages
and value messages of type play.api.i18n.Messages
match expected type play.api.i18n.Messages 
```

I tried various solution without any luck. Am I doing something wrong or have something to do with play-bootstrap and Java? Here's my template code:

```scala
@(productForm: Form[Product])

@import b3.vertical.fieldConstructor


@main("Product Form") {
	<h1>Product Form</h1>
	@b3.form(routes.ProductsController.save()) {
		<fieldset>
			@b3.text(productForm("ean"), '_label -> "EAN")
			@b3.text(productForm("name"), '_label -> "Name")
			@b3.textarea(productForm("description"), '_label -> "Description", 'rows -> 3 )
		</fieldset>
		@b3.submit('class -> "btn btn-primary"){ <span class="glyphicon glyphicon-ok"></span> Save }
		@b3.button('class -> "btn btn-danger", 'href -> "@routes.Products.index()"){ <span class="glyphicon glyphicon-remove"></span> Cancel }
	}
}
```

**Comment by adrianhurt** [comment]
Sorry, but I'm not very used to use the Java version for Play since a long time. I have a very simple project that it works to work for me. Could you please create any simple github project to see the error?

**Comment by adrianhurt** [comment]
Meanwhile, I close this issue. Feel free to reopen if you need it.
