### ISSUE TITLE
module not found: which resolver should i use?

### ISSUE THREAD

**Issue by mohitjaggi** [adrianhurt/play-bootstrap#75]
[info] Resolving com.adrianhurt#play-bootstrap3_2.11;1.1-P25-B3 ...
[warn] 	module not found: com.adrianhurt#play-bootstrap3_2.11;1.1-P25-B3
[warn] ==== local: tried
[warn]   /Users/mohit/.ivy2/local/com.adrianhurt/play-bootstrap3_2.11/1.1-P25-B3/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/adrianhurt/play-bootstrap3_2.11/1.1-P25-B3/play-bootstrap3_2.11-1.1-P25-B3.pom
[warn] ==== activator-launcher-local: tried
[warn]   /Users/mohit/code/datagears-play/repository/com.adrianhurt/play-bootstrap3_2.11/1.1-P25-B3/ivys/ivy.xml
[warn] ==== activator-local: tried
[warn]   /Users/mohit/code/activator-dist-1.3.10/repository/com.adrianhurt/play-bootstrap3_2.11/1.1-P25-B3/ivys/ivy.xml
[warn] ==== typesafe-releases: tried
[warn]   http://repo.typesafe.com/typesafe/releases/com/adrianhurt/play-bootstrap3_2.11/1.1-P25-B3/play-bootstrap3_2.11-1.1-P25-B3.pom
[warn] ==== typesafe-ivy-releasez: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.adrianhurt/play-bootstrap3_2.11/1.1-P25-B3/ivys/ivy.xml
[warn] ==== Atlassian Releases: tried
[warn]   https://maven.atlassian.com/public/com/adrianhurt/play-bootstrap3_2.11/1.1-P25-B3/play-bootstrap3_2.11-1.1-P25-B3.pom
[warn] ==== scalaz-bintray: tried
[warn]   http://dl.bintray.com/scalaz/releases/com/adrianhurt/play-bootstrap3_2.11/1.1-P25-B3/play-bootstrap3_2.11-1.1-P25-B3.pom
[warn] ==== sonatype-snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/com/adrianhurt/play-bootstrap3_2.11/1.1-P25-B3/play-bootstrap3_2.11-1.1-P25-B3.pom
[warn] ==== jcenter: tried
[warn]   https://jcenter.bintray.com/com/adrianhurt/play-bootstrap3_2.11/1.1-P25-B3/play-bootstrap3_2.11-1.1-P25-B3.pom
[info] Resolving net.contentobjects.jnotify#jnotify;0.94-play-1 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.adrianhurt#play-bootstrap3_2.11;1.1-P25-B3: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::

**Comment by mohitjaggi** [comment]
the code example on https://adrianhurt.github.io/play-bootstrap/ was wrong. there is no "3" after bootstrap in the name. removed that and works fine now!

**Comment by adrianhurt** [comment]
Hi @mohitjaggi. Precisely, there in the docs it is specified that artifact `play-bootstrap3` is only for older versions. I suppose I should simply remove that mention, since versions previous than 1.0 are old now and it's also specified in the changelog page.

**Comment by mohitjaggi** [comment]
You are right. I was reading too fast!

Mohit Jaggi
Founder,
Data Orchard LLC
www.dataorchardllc.com
