### ISSUE TITLE
table input

### ISSUE THREAD

**Issue by mohitjaggi** [adrianhurt/play-bootstrap#76]
I want to create a form with a table input. Is there a way to do something like the play framework's
@helper.repeat(...) ?

**Comment by adrianhurt** [comment]
Hi @mohitjaggi. The helper `repeat` should work as it is explained at the Play docs, but using b3 helpers when needed. It's independent from how the fields are rendered into HTML. So try it as the following example. If it doesn't work, just tell me.

```
@helper.repeat(myForm("emails"), min = 1) { emailField =>
    @b3.text(emailField, … )
}
```

**Comment by mohitjaggi** [comment]
OK. I did @b3.repeat instead of @helper.repeat. My bad.
