### ISSUE TITLE
Support Play 2.6.0-M1 and Scala 2.12

### ISSUE THREAD

**Issue by mslinn** [adrianhurt/play-bootstrap#78]
Most of the changes I have found regarding Play 2.6.0-M1 have been fairly simple to deal with.

**Comment by adrianhurt** [comment]
Hi @mslinn. Thanks for your interest. I think it's still soon but feel free trying to create a PR with folders `core-play26` and `play26-bootstrap3`. The main changes affecting us I can see are here:
https://www.playframework.com/documentation/2.6.x/MessagesMigration26

**Comment by adrianhurt** [comment]
Now it's updated. Please, check [this](https://github.com/adrianhurt/play-bootstrap/pull/84#issuecomment-307658388)
