### ISSUE TITLE
b3.hidden should also take field

### ISSUE THREAD

**Issue by mkurz** [adrianhurt/play-bootstrap#86]
Right now the `b3.hidden` field takes following arguments:
`@(name: Any, value: Any, args: (Symbol, Any)*)`
so you have to pass the `name` and `value` **explicitly**.

Please add a version like:
`@(field: Field, args: (Symbol,Any)*)`

So we could simple "hide" a field by changing it from:
`@b3.text( fooForm("name"), '_label -> "Name", 'placeholder -> "John Doe" )`
to
`@b3.hidden( fooForm("name"), '_label -> "Name", 'placeholder -> "John Doe" )`
(The `_label` ~~and `placeholder`~~ etc. could just be ignored)

**Comment by mkurz** [comment]
(Updated. Sorry - I hit the "Submit" button to early)

**Comment by mkurz** [comment]
I think arguments starting with `_` (like `_label`) can then be ignored, but others should not (E.g I still want to be able to add a `'class` or html5 data attributes to the hidden field).

**Comment by mkurz** [comment]
Thanks! I will try it next week.

**Comment by adrianhurt** [comment]
Thanks, and sorry for the delay, it's now implemented in the new versions. Please, check [this](https://github.com/adrianhurt/play-bootstrap/pull/84#issuecomment-307658388).

**Comment by mkurz** [comment]
@adrianhurt I found a but:
When I write:
```
@b3.hidden(myForm("somefield"), 'class -> "something")
```

I get
```
<input type="hidden" name="Form.Field(somefield)" value="(&#x27;class,something)" >
```

Removing `, 'class -> "something"` fixes the problem. Same happens if I write `'_label -> "something"`

**Comment by adrianhurt** [comment]
It's strange. It works for me using `'class` and `'_label`. Which version of play-bootstrap are you using? Have you tried cleaning the project?

**Comment by mkurz** [comment]
@adrianhurt I am **sure** now **this definitely is a bug**. If you test with a `play.data.Field` of a PlayJava project instead using a `play.api.data.Field` from PlayScala you will see the error too :wink: Please see #87

**Comment by adrianhurt** [comment]
Thanks for the solution and PR. Please, check it when you can.
