### ISSUE TITLE
com.adrianhurt#play-bootstrap_2.12;1.1.1-P25-B3: not found

### ISSUE THREAD

**Issue by sanjeevghimire** [adrianhurt/play-bootstrap#91]
my build.sbt looks like following

```
name := """watson-language-translator-play-api"""
organization := "com.ibm"

version := "1.0-SNAPSHOT"

lazy val root = (project in file(".")).enablePlugins(PlayScala)

scalaVersion := "2.12.2"


libraryDependencies += guice
libraryDependencies += "org.scalatestplus.play" %% "scalatestplus-play" % "3.0.0" % Test

// Adds additional packages into Twirl
//TwirlKeys.templateImports += "com.ibm.controllers._"

// Adds additional packages into conf/routes
// play.sbt.routes.RoutesKeys.routesImport += "com.ibm.binders._"


libraryDependencies += "com.adrianhurt" %% "play-bootstrap" % "1.1.1-P25-B3" exclude("org.webjars", "jquery")
libraryDependencies +=  "org.webjars" % "jquery" % "3.1.1"
```

Error:Error while importing SBT project:<br/>...<br/><pre>[info] Resolving org.ow2.asm#asm;5.0.3 ...
[info] Resolving org.ow2.asm#asm-tree;5.0.3 ...
[info] Resolving org.ow2.asm#asm-analysis;5.0.3 ...
[info] Resolving org.ow2.asm#asm-util;5.0.3 ...
[info] Resolving org.scala-lang#scala-compiler;2.12.2 ...
[info] Resolving jline#jline;2.14.3 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.adrianhurt#play-bootstrap_2.12;1.1.1-P25-B3: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.adrianhurt:play-bootstrap_2.12:1.1.1-P25-B3 (/Users/sanjeevghimire/Documents/workspace/watson-language-translator-play-api/build.sbt#L21-22)
[warn] 		  +- com.ibm:watson-language-translator-play-api_2.12:1.0-SNAPSHOT
[trace] Stack trace suppressed: run 'last *:update' for the full output.
[trace] Stack trace suppressed: run 'last *:ssExtractDependencies' for the full output.
[error] (*:update) sbt.ResolveException: unresolved dependency: com.adrianhurt#play-bootstrap_2.12;1.1.1-P25-B3: not found
[error] (*:ssExtractDependencies) sbt.ResolveException: unresolved dependency: com.adrianhurt#play-bootstrap_2.12;1.1.1-P25-B3: not found
[error] Total time: 2 s, completed Jun 28, 2017 1:18:48 PM</pre><br/>See complete log in <a href="/Users/sanjeevghimire/Library/Logs/IdeaIC2016.2/sbt.last.log">/Users/sanjeevghimire/Library/Logs/IdeaIC2016.2/sbt.last.log</a>

**Comment by adrianhurt** [comment]
Hi @sanjeevghimire. I'm not totally sure, but I suspect it's due to the scala version. The plugin for version prior to 1.2 is compiled for scala 2.11. The new version 1.2 (still a snapshot but I'll release it in some days) is compiled for scala 2.12. So try to use 1.2-P25-B3-SNAPSHOT.

**Comment by sanjeevghimire** [comment]
thanks @adrianhurt . i changed to 2.11 and it works.

**Comment by sanjeevghimire** [comment]
Is there a sample play bootstrap github example?

**Comment by adrianhurt** [comment]
Yes! Each version has its own sample. Check [this](https://github.com/adrianhurt/play-bootstrap/tree/master/play25-bootstrap3/sample).

You can also check other of my repos: (Play Multidomain Auth](https://github.com/adrianhurt/play-multidomain-auth).

Or simply use the GitHub's global finder: [try this](https://github.com/search?q=play-bootstrap+filename%3Abuild.sbt&type=Repositories&utf8=✓).
