### ISSUE TITLE
Play 2.6 for scala 2.11

### ISSUE THREAD

**Issue by nafg** [adrianhurt/play-bootstrap#93]
Any reason not to cross-build?

**Comment by adrianhurt** [comment]
None! 👍  I've just release a RC1 version and I've added scala 2.11.8 for version for Play 2.6.

**Comment by mkurz** [comment]
`2.11.11` is the latest release of the Scala `2.11.x` branch - see #94

**Comment by adrianhurt** [comment]
Thanks!
