### ISSUE TITLE
Multifield documentation goes to a dead page

### ISSUE THREAD

**Issue by jducoeur** [adrianhurt/play-bootstrap#98]
In general, the doc links are a little flaky -- some things are pointing to "singleton" paths, but only exist in "versioned" paths.  Most notably, all the links to Multifield point to http://adrianhurt.github.io/play-bootstrap/multifield -- which doesn't exist, you need to actually use, eg, http://adrianhurt.github.io/play-bootstrap/1.2-P26-B3/multifield/

**Comment by adrianhurt** [comment]
Hi @jducoeur, as we have lots of different versions, the doc links are caught by JS and the version is added. It's true, I should have a link for http://adrianhurt.github.io/play-bootstrap/multifield (and the rest ones) and redirect them to the last version. However, I've just tried the links that points to multifield section and they work. The only one I've see it's broken is the last one at the "Documentation" section. The rest are caught correctly by JS and redirected to the corresponding version of the library. Do you have JS activated? Could you give me more information?

I'll try to fix it this weekend

**Comment by jducoeur** [comment]
Hmm, now that's odd.  I'm *pretty* sure I got the 404 from at least one of the links on the "Multifield support" section on the front page.  (Since I specifically wanted to reproduce the date-range control shown there.)  But now it doesn't repro for me.

It hadn't occurred to me that those links were being intercepted and redirected.  I'm now wondering if there was a quiet error at the JS level -- a problem fetching a script or something.  Or possibly an error from the datepicker?  I was messing around with it a bunch, inspecting the HTML and suchlike; depending on how the redirect works, I could believe that I hit an edge case that caused JS to choke.  (It's certainly enabled, but it's not *that* hard to cause JS errors that cause subtle misbehavior.)

I'll write back if I come up with an actual recipe; right now, it's being a bit mysterious...

**Comment by adrianhurt** [comment]
Hi @jducoeur. I've just updated the docs with the final release for version 1.2 and I fixed that broken link. I've also added the redirections for /multifield and any other "version agnostic" links to the last version. I suppose it's also an advantage for SEO 👍 

If you see something wrong, just let me know.

**Comment by jducoeur** [comment]
Will do -- thanks!

(And thanks for the library: it's quite delightful, and makes for much cleaner templates...)
